GET http://localhost:8080/tasks

###

POST http://localhost:8080/tasks
Content-Type: application/json

{
  "id": "3",
  "description": "Buy milk",
  "note": "Remember to check expiration date",
  "applications": ["Shopping list"]
}

###

GET http://localhost:8080/tasks/3

###

DELETE http://localhost:8080/tasks/3